### ISSUE TITLE
"Try out" not working

### ISSUE THREAD

**Issue by agowa** [InterNetX/internetx-swagger-files#10]
Try out is currently not working as the Authentication information is not defined.

**Comment by mschrieck** [comment]
You have some more Informationen?

You got an error or something ?

**Comment by agowa** [comment]
The authentication is missing. Other swagger/openAPIs have a button "Authenticate" at the top left. This one doesn't.

Something like this is missing:
```
openapi: 3.0.0
...
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
security:
  - basicAuth: []  # <-- use the same name here
```

According to the other help pages these exist:
- https://swagger.io/docs/specification/authentication/basic-authentication/ `Authorization: Basic (base64 of username:password)`-Header
- https://swagger.io/docs/specification/authentication/cookie-authentication/ With cookie header
- https://swagger.io/docs/specification/authentication/api-keys/ `X-Domainrobot-SessionId: $sessionID`

**Comment by TamaoX8** [comment]
Unfortunately, this does not work at the moment. We recommend that you use PostMan.
