### ISSUE TITLE
Api Endpoint /domain/_search returns not all elements, bulk max without paging

### ISSUE THREAD

**Issue by Zeg0** [InterNetX/internetx-swagger-files#18]
Hello,

The POST `/domain/_search` endpoint should return a list of domains. In my case i have 160 domains in AutoDNS, however the api returns exactly 100 elements. In the [Swagger-Doku](https://raw.githubusercontent.com/InterNetX/domainrobot-api/master/src/domainrobot.json) i found a header `X-Domainrobot-Bulk-Limit` which propably helps in my case if i just set it to a very large number... However a better approach would be an api endpoint that allows real paging.

**Comment by Ephenodrom** [comment]
Hello @Zeg0,

How does your body of the POST request look like ?

The amount of entities fetched via this endpoint is defined via the "view" field within the json body. Example :

```json
{
    "filters": [
        {
            "key": "name",
            "operator": "LIKE",
            "value": "%mydomain%"
        }
    ],
    "view": {
        "children": 1,
        "limit": 1000,
        "offset": 0,
    },
    "orders": [
        {
            "key": "created",
            "type": "ASC"
        }
    ]
}
```

The view can then be used via the limit and offeset parameter to create a pagination.

The response should look similar to this :

```json
{
  "stid": "20240223-app3-dev-3587",
  "status": {
    "code": "S0105",
    "text": "Domain-Daten wurden erfolgreich ermittelt.",
    "type": "SUCCESS"
  },
  "object": {
    "type": "Domain",
    "summary": 102
  },
  "data": [
    {
      "created": "2014-10-29T13:58:56.000+0100",
      "updated": "2023-05-17T14:15:53.000+0200",
      "owner": {
        "context": 4,
        "user": "myuser"
      },
      "name": "mydomain.de",
      "payable": "2024-02-29T23:59:59.000+0100"
    }
  ]
}
```

The "object" field holds a "summary" field that respresents the amount of entities that belong to your user. With the limit and the summary, the maximum number of pages can then be calculated.

If there are any questions left, feel free to comment.

**Comment by Zeg0** [comment]
Ahhh i see - i thought i needed the header, but your recommended body `"view"` worked just fine. I left that completely empty previously.

Now it works - thank you!
