### ISSUE TITLE
Question for domain creation /domain endpoint

### ISSUE THREAD

**Issue by Zeg0** [InterNetX/internetx-swagger-files#19]
Hi,

I try to create and register some new domains via the domainrobot API endpoint `/domain`.

Firstly i already own a domain `abc.de` which is registered in my internetx autodns.

My api-client should register some new subdomains like `deeplink.subdomain.abc.de` and `subdomain.abc.de`.

I send the post body like this:
```
{
  "name": "deeplink.subdomain.abc.de",
  "nameServers": [
    {
      "name": "a.ns14.net"
    },
    {
      "name": "b.ns14.net"
    },
    {
      "name": "c.ns14.net"
    },
    {
      "name": "d.ns14.net"
    }
  ],
  "ownerc": {
    "id": 123456789
  },
  "adminc": {
    "id": 123456789
  },
  "techc": {
    "id": 123456789
  },
  "zonec": {
    "id": 123456789
  }
}
```
that fails with `ERROR: {"stid":"20240223-app3-180557","messages":[{"text":"Fehler beim Lesen des Auftrages.","objects":[{"type":"payload","value":""}],"code":"EF00000","status":"ERROR"}],"status":{"type":"ERROR"}}`

when i try to create the `subdomain.abc.de` without the "deeplink" part in front the error message changes to:

`ERROR: {"stid":"20240223-app3-180564","messages":[{"text":"Ungueltige TLD.","objects":[{"type":"name","value":"abc.de"}],"code":"EF01001","status":"ERROR"}],"status":{"code":"E0101","text":"Domain konnte nicht registriert werden.","type":"ERROR"},"object":{"type":"Domain","value":"subdomain.abc.de"}}`

How can i accomplish to register my subdomains?

Thanks for any help with this

**Comment by DasKutti** [comment]
@Zeg0 With AutoDNS you register domains under TLDs offered by InterNetX. Such names are  domain.de or domain.eu. I assume that you want to create subdomains within your registered domains
.
Do you use the InterNetX name service? If so, you can manages your zones via the API. Via /zone/ route. The API documentation will help you here. If you have any further questions i recommend you to share your questions with the support team of InterNetX.

**Comment by Zeg0** [comment]
So you recommend using this request: `/zone` with a jsonBody formed from a zone object. I found in this api description (`https://github.com/InterNetX/domainrobot-api/blob/master/src/domainrobot.json` line 20593+) that the `/zone` endpoint simply wants a zone body and some headers. After looking up what a zone body object might contain i found this example:
```
{
  "Created": "0001-01-01T00:00:00Z",
  "Updated": "0001-01-01T00:00:00Z",
  "Origin": "",
  "IDN": "",
  "DNSSec": false,
  "NameserverGroup": "",
  "AllowTransfer": false,
  "LogID": 0,
  "Comment": "",
  "DomainSafe": false,
  "Source": "",
  "SourceVirtualHostname": "",
  "Nameservers": [ { "Name": "a.ns14.net", "TTL": 3600, "IPAddresses": [ "127.0.0.1" , ... ] } , ... ],
  "WWWInclude": false,
  "VirtualNameserver": false,
  "FreeText": null,
  "RoID": 0,
  "Grants": [ "" , "" , ... ],
  "SOA": null,
  "Main": [ "Address":"127.0.0.1" , "TTL":3600 ],
  "Action": "",
  "ResourceRecords": [ ... ??? ... ]
}
```

I don't know how i can register a subdomain for my existing domain with that. I would appreciate if you could give me an example how to use the api here. Thank you

**Comment by Zeg0** [comment]
Close this issue.

Internetx support gave me this example to PATCH an existing domain i own, to create or remove additional CNAME (or other) entries in the zonefile of my domain to essentially manage my subdomains:

```
PATCH /zone/example-domain.com/a.ns14.net
(with the login token as previously)

BODY
#########
{
  "resourceRecordsRem": [
    {
      "name": "custom_entry_name_to_be_deleted",
      "type": "CNAME",
      "value": "external.example-domain.com."
    }
  ],
  "resourceRecordsAdd": [
    {
      "name": "custom_entry_name_to_be_added",
      "type": "CNAME",
      "ttl": 86400,
      "value": "www.example-domain.com."
    }
  ]
}
#########

```

Hope this might help someone
