### ISSUE TITLE
Error codes not documented

### ISSUE THREAD

**Issue by agowa** [InterNetX/internetx-swagger-files#9]
The error codes are not documented within the open api specification.

**Comment by Ephenodrom** [comment]
There is a seperate documentation that includes some of the error codes. Example here : https://help.internetx.com/display/APIXMLEN/Domain+Create

I think The Open API documentation is not 100% suitable for such large APIs to document everything to the smallest detail. Therefore a separate documentation with extended information exists.

**Comment by agowa** [comment]
Just come across this issue again this time searching for another undocumented error code: "E0202002"
`status code=400: {"stid":"20210326-app4-169456","status":{"code":"E0202002","text":"Zone konnte auf dem Nameserver nicht aktualisiert werden.","type":"ERROR"}}`

**Comment by TamaoX8** [comment]
We have added the 'E0202002'  error code to the our documentation. As mentioned above, you can find the error codes and further information under https://help.internetx.com/display/APIXMLEN/Zone+Create
